services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    external: true
